### ISSUE TITLE
Screen saver comes on when artist slideshow is on

### ISSUE THREAD

**Issue by snake3ca** [pkscout/script.artistslideshow#51]
On kodi 18 the screen saver comes on when Artist slide show is playing.  Not sure if this is by design or not but was not an issue in Kodi 17.  Would be nice if when Artist slideshow is on the screen the screen saver and monitor sleep mode were disabled.

**Comment by pkscout** [comment]
I've have to check on this.  I was able to duplicate what you are seeing on my test Windows machine using Kodi 18.  I don't use the screensaver, so that never got tested.  If AS kept the screensaver from activating in 17, it wasn't anything intentional, so I'll have to see if there were changes in Kodi 18 that might have changed the behavior.

**Comment by snake3ca** [comment]
Perfect thank you
