### ISSUE TITLE
Artist slideshow update issue

### ISSUE THREAD

**Issue by Dutchy-79** [pkscout/script.artistslideshow#54]
Hi,

I haven't used my Pi music setup for a while and now I have a update issue. Slideshow updated to 3.2.1 and skin is the 18.5 Estuary that was working before the update. 

I can't find a solution yet so hopefully you can help me out. 

Best regards, 

Dutchy

**Comment by pkscout** [comment]
"not working" is too vague to help.  I really need a detailed description of your issue and a link to a Kodi log (that has both Kodi's debug option enabled *and* debug logging in the AS settings enabled as well) that shows the problem.

**Comment by Dutchy-79** [comment]
Sorry, I thought I explained it.

It says that slideshow is updated and I have a not working skin. Though I have been working with the same skin before and it hasn't changed.

**Comment by pkscout** [comment]
The Estuary in 18.5 should be compatible with AS 3.x. I worked with the Kodi folks to make sure Estuary was compatible with both versions.  That said, I know there was a typo in the skin that could cause problems with AS.  That was fixed in 18.6, so you might update to Kodi 18.6 and see if that resolves that.

**Comment by Dutchy-79** [comment]
Thanks, that fixed it.
